# app.yaml
runtime: nodejs20
service: frontend
instance_class: F1

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)